// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MS_Test/Freezbee.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MSTest.Proto {

  /// <summary>Holder for reflection information generated from MS_Test/Freezbee.proto</summary>
  public static partial class FreezbeeReflection {

    #region Descriptor
    /// <summary>File descriptor for MS_Test/Freezbee.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FreezbeeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNU19UZXN0L0ZyZWV6YmVlLnByb3RvEg1NU19UZXN0LnByb3RvIkUKCEZy",
            "ZWV6YmVlEhAKCGlkTW9kZWxlGAEgASgFEhIKCm5hbWVNb2RlbGUYAiABKAkS",
            "EwoLZ2FtbWVNb2RlbGUYAyABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MSTest.Proto.Freezbee), global::MSTest.Proto.Freezbee.Parser, new[]{ "IdModele", "NameModele", "GammeModele" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Freezbee : pb::IMessage<Freezbee>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Freezbee> _parser = new pb::MessageParser<Freezbee>(() => new Freezbee());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Freezbee> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MSTest.Proto.FreezbeeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee(Freezbee other) : this() {
      idModele_ = other.idModele_;
      nameModele_ = other.nameModele_;
      gammeModele_ = other.gammeModele_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee Clone() {
      return new Freezbee(this);
    }

    /// <summary>Field number for the "idModele" field.</summary>
    public const int IdModeleFieldNumber = 1;
    private int idModele_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdModele {
      get { return idModele_; }
      set {
        idModele_ = value;
      }
    }

    /// <summary>Field number for the "nameModele" field.</summary>
    public const int NameModeleFieldNumber = 2;
    private string nameModele_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NameModele {
      get { return nameModele_; }
      set {
        nameModele_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gammeModele" field.</summary>
    public const int GammeModeleFieldNumber = 3;
    private string gammeModele_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GammeModele {
      get { return gammeModele_; }
      set {
        gammeModele_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Freezbee);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Freezbee other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdModele != other.IdModele) return false;
      if (NameModele != other.NameModele) return false;
      if (GammeModele != other.GammeModele) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdModele != 0) hash ^= IdModele.GetHashCode();
      if (NameModele.Length != 0) hash ^= NameModele.GetHashCode();
      if (GammeModele.Length != 0) hash ^= GammeModele.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdModele != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdModele);
      }
      if (NameModele.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameModele);
      }
      if (GammeModele.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GammeModele);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdModele != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdModele);
      }
      if (NameModele.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameModele);
      }
      if (GammeModele.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GammeModele);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdModele != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdModele);
      }
      if (NameModele.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameModele);
      }
      if (GammeModele.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GammeModele);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Freezbee other) {
      if (other == null) {
        return;
      }
      if (other.IdModele != 0) {
        IdModele = other.IdModele;
      }
      if (other.NameModele.Length != 0) {
        NameModele = other.NameModele;
      }
      if (other.GammeModele.Length != 0) {
        GammeModele = other.GammeModele;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdModele = input.ReadInt32();
            break;
          }
          case 18: {
            NameModele = input.ReadString();
            break;
          }
          case 26: {
            GammeModele = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdModele = input.ReadInt32();
            break;
          }
          case 18: {
            NameModele = input.ReadString();
            break;
          }
          case 26: {
            GammeModele = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
