// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Config/Proto/MS_RD/Freezbee.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MSRD.Proto {

  /// <summary>Holder for reflection information generated from Config/Proto/MS_RD/Freezbee.proto</summary>
  public static partial class FreezbeeReflection {

    #region Descriptor
    /// <summary>File descriptor for Config/Proto/MS_RD/Freezbee.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FreezbeeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFDb25maWcvUHJvdG8vTVNfUkQvRnJlZXpiZWUucHJvdG8SC01TX1JELnBy",
            "b3RvIqsBCghGcmVlemJlZRIQCghpZE1vZGVsZRgBIAEoBRISCgpuYW1lTW9k",
            "ZWxlGAIgASgJEhMKC2dhbW1lTW9kZWxlGAMgASgJEhMKC2Rlc2NyaXB0aW9u",
            "GAQgASgJEgwKBHBVaHQYBSABKAUSFAoMaWRJbmdyZWRpZW50GAYgASgFEhAK",
            "CGdyYW1tYWdlGAcgASgFEhkKEWlkQ2FyYWN0ZXJpc3RpcXVlGAggASgFYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MSRD.Proto.Freezbee), global::MSRD.Proto.Freezbee.Parser, new[]{ "IdModele", "NameModele", "GammeModele", "Description", "PUht", "IdIngredient", "Grammage", "IdCaracteristique" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Freezbee : pb::IMessage<Freezbee>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Freezbee> _parser = new pb::MessageParser<Freezbee>(() => new Freezbee());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Freezbee> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MSRD.Proto.FreezbeeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee(Freezbee other) : this() {
      idModele_ = other.idModele_;
      nameModele_ = other.nameModele_;
      gammeModele_ = other.gammeModele_;
      description_ = other.description_;
      pUht_ = other.pUht_;
      idIngredient_ = other.idIngredient_;
      grammage_ = other.grammage_;
      idCaracteristique_ = other.idCaracteristique_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Freezbee Clone() {
      return new Freezbee(this);
    }

    /// <summary>Field number for the "idModele" field.</summary>
    public const int IdModeleFieldNumber = 1;
    private int idModele_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdModele {
      get { return idModele_; }
      set {
        idModele_ = value;
      }
    }

    /// <summary>Field number for the "nameModele" field.</summary>
    public const int NameModeleFieldNumber = 2;
    private string nameModele_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NameModele {
      get { return nameModele_; }
      set {
        nameModele_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gammeModele" field.</summary>
    public const int GammeModeleFieldNumber = 3;
    private string gammeModele_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GammeModele {
      get { return gammeModele_; }
      set {
        gammeModele_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pUht" field.</summary>
    public const int PUhtFieldNumber = 5;
    private int pUht_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PUht {
      get { return pUht_; }
      set {
        pUht_ = value;
      }
    }

    /// <summary>Field number for the "idIngredient" field.</summary>
    public const int IdIngredientFieldNumber = 6;
    private int idIngredient_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdIngredient {
      get { return idIngredient_; }
      set {
        idIngredient_ = value;
      }
    }

    /// <summary>Field number for the "grammage" field.</summary>
    public const int GrammageFieldNumber = 7;
    private int grammage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Grammage {
      get { return grammage_; }
      set {
        grammage_ = value;
      }
    }

    /// <summary>Field number for the "idCaracteristique" field.</summary>
    public const int IdCaracteristiqueFieldNumber = 8;
    private int idCaracteristique_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdCaracteristique {
      get { return idCaracteristique_; }
      set {
        idCaracteristique_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Freezbee);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Freezbee other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdModele != other.IdModele) return false;
      if (NameModele != other.NameModele) return false;
      if (GammeModele != other.GammeModele) return false;
      if (Description != other.Description) return false;
      if (PUht != other.PUht) return false;
      if (IdIngredient != other.IdIngredient) return false;
      if (Grammage != other.Grammage) return false;
      if (IdCaracteristique != other.IdCaracteristique) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdModele != 0) hash ^= IdModele.GetHashCode();
      if (NameModele.Length != 0) hash ^= NameModele.GetHashCode();
      if (GammeModele.Length != 0) hash ^= GammeModele.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (PUht != 0) hash ^= PUht.GetHashCode();
      if (IdIngredient != 0) hash ^= IdIngredient.GetHashCode();
      if (Grammage != 0) hash ^= Grammage.GetHashCode();
      if (IdCaracteristique != 0) hash ^= IdCaracteristique.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdModele != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdModele);
      }
      if (NameModele.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameModele);
      }
      if (GammeModele.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GammeModele);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (PUht != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PUht);
      }
      if (IdIngredient != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(IdIngredient);
      }
      if (Grammage != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Grammage);
      }
      if (IdCaracteristique != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(IdCaracteristique);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdModele != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdModele);
      }
      if (NameModele.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameModele);
      }
      if (GammeModele.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GammeModele);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (PUht != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PUht);
      }
      if (IdIngredient != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(IdIngredient);
      }
      if (Grammage != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Grammage);
      }
      if (IdCaracteristique != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(IdCaracteristique);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdModele != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdModele);
      }
      if (NameModele.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameModele);
      }
      if (GammeModele.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GammeModele);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (PUht != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PUht);
      }
      if (IdIngredient != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdIngredient);
      }
      if (Grammage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Grammage);
      }
      if (IdCaracteristique != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdCaracteristique);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Freezbee other) {
      if (other == null) {
        return;
      }
      if (other.IdModele != 0) {
        IdModele = other.IdModele;
      }
      if (other.NameModele.Length != 0) {
        NameModele = other.NameModele;
      }
      if (other.GammeModele.Length != 0) {
        GammeModele = other.GammeModele;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.PUht != 0) {
        PUht = other.PUht;
      }
      if (other.IdIngredient != 0) {
        IdIngredient = other.IdIngredient;
      }
      if (other.Grammage != 0) {
        Grammage = other.Grammage;
      }
      if (other.IdCaracteristique != 0) {
        IdCaracteristique = other.IdCaracteristique;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdModele = input.ReadInt32();
            break;
          }
          case 18: {
            NameModele = input.ReadString();
            break;
          }
          case 26: {
            GammeModele = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 40: {
            PUht = input.ReadInt32();
            break;
          }
          case 48: {
            IdIngredient = input.ReadInt32();
            break;
          }
          case 56: {
            Grammage = input.ReadInt32();
            break;
          }
          case 64: {
            IdCaracteristique = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdModele = input.ReadInt32();
            break;
          }
          case 18: {
            NameModele = input.ReadString();
            break;
          }
          case 26: {
            GammeModele = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 40: {
            PUht = input.ReadInt32();
            break;
          }
          case 48: {
            IdIngredient = input.ReadInt32();
            break;
          }
          case 56: {
            Grammage = input.ReadInt32();
            break;
          }
          case 64: {
            IdCaracteristique = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
